/* ============================================================================
   MasterPOS — 03_Sales_POS.sql
   Orders, OrderLines (per-item KOT note + station), OrderPayments (the
   Split Payment multi-tender ledger), KOT print log.
   Depends on: 01_Core_Auth.sql, 02_Masters.sql
   ============================================================================ */

SET QUOTED_IDENTIFIER ON;
GO

-- ---------------------------------------------------------------------------
-- Sales.Orders
-- One row per bill/table order — whether it's a Trading walk-in sale or a
-- Cafe table order. TableId is only populated for Cafe DineIn orders.
-- ---------------------------------------------------------------------------
CREATE TABLE Sales.Orders
(
    Id                UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Orders_Id DEFAULT (NEWSEQUENTIALID()),
    CompanyId         UNIQUEIDENTIFIER NOT NULL,
    BranchId          UNIQUEIDENTIFIER NOT NULL,
    OrderNumber       NVARCHAR(30)     NOT NULL,        -- "ORD-10231" — human-facing, generated by the app
    OrderType         NVARCHAR(20)     NOT NULL CONSTRAINT CK_Orders_OrderType
                          CHECK (OrderType IN ('DineIn', 'Takeaway', 'Delivery', 'Counter')),
    TableId           UNIQUEIDENTIFIER NULL,             -- Cafe DineIn only
    GuestCount        INT              NULL,
    CustomerId        UNIQUEIDENTIFIER NULL,             -- FK -> Masters.Parties, nullable = walk-in
    CashierUserId     UNIQUEIDENTIFIER NOT NULL,
    Status            NVARCHAR(20)     NOT NULL CONSTRAINT DF_Orders_Status DEFAULT ('Open')
                          CONSTRAINT CK_Orders_Status CHECK (Status IN ('Open', 'PartiallyPaid', 'Paid', 'Cancelled', 'OnHold')),
    SubTotalAmount    DECIMAL(18,2)    NOT NULL CONSTRAINT DF_Orders_SubTotalAmount DEFAULT (0),
    DiscountAmount    DECIMAL(18,2)    NOT NULL CONSTRAINT DF_Orders_DiscountAmount DEFAULT (0),
    VatAmount         DECIMAL(18,2)    NOT NULL CONSTRAINT DF_Orders_VatAmount DEFAULT (0),
    RoundOffAmount    DECIMAL(18,2)    NOT NULL CONSTRAINT DF_Orders_RoundOffAmount DEFAULT (0),
    GrandTotalAmount  DECIMAL(18,2)    NOT NULL CONSTRAINT DF_Orders_GrandTotalAmount DEFAULT (0),
    OpenedAtUtc       DATETIME2(3)     NOT NULL CONSTRAINT DF_Orders_OpenedAtUtc DEFAULT (SYSUTCDATETIME()),
    ClosedAtUtc       DATETIME2(3)     NULL,
    CreatedAtUtc      DATETIME2(3)     NOT NULL CONSTRAINT DF_Orders_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
    CreatedByUserId   UNIQUEIDENTIFIER NULL,
    ModifiedAtUtc     DATETIME2(3)     NULL,
    ModifiedByUserId  UNIQUEIDENTIFIER NULL,
    IsDeleted         BIT              NOT NULL CONSTRAINT DF_Orders_IsDeleted DEFAULT (0),
    CONSTRAINT PK_Orders PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_Orders_Company FOREIGN KEY (CompanyId) REFERENCES Core.Companies(Id),
    CONSTRAINT FK_Orders_Branch FOREIGN KEY (BranchId) REFERENCES Core.Branches(Id),
    CONSTRAINT FK_Orders_Table FOREIGN KEY (TableId) REFERENCES Masters.DiningTables(Id),
    CONSTRAINT FK_Orders_Customer FOREIGN KEY (CustomerId) REFERENCES Masters.Parties(Id),
    CONSTRAINT FK_Orders_Cashier FOREIGN KEY (CashierUserId) REFERENCES Auth.Users(Id),
    CONSTRAINT UQ_Orders_Company_OrderNumber UNIQUE (CompanyId, OrderNumber)
);
GO
CREATE INDEX IX_Orders_Company_Status ON Sales.Orders(CompanyId, Status) WHERE IsDeleted = 0;
CREATE INDEX IX_Orders_TableId ON Sales.Orders(TableId) WHERE TableId IS NOT NULL AND IsDeleted = 0;
GO

-- ---------------------------------------------------------------------------
-- Sales.OrderLines
-- Note: per-item note field (used before "Save KOT"), and KotStation/
-- KotStatus snapshotted from the product at add-time so a later edit to the
-- product master doesn't rewrite history on an already-punched order.
-- ---------------------------------------------------------------------------
CREATE TABLE Sales.OrderLines
(
    Id                UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_OrderLines_Id DEFAULT (NEWSEQUENTIALID()),
    OrderId           UNIQUEIDENTIFIER NOT NULL,
    ProductId         UNIQUEIDENTIFIER NOT NULL,
    Quantity          DECIMAL(18,3)    NOT NULL,
    UnitPrice         DECIMAL(18,2)    NOT NULL,
    Note              NVARCHAR(300)    NULL,             -- e.g. "Less spicy, no coriander"
    KotStation        NVARCHAR(20)     NULL CONSTRAINT CK_OrderLines_KotStation
                          CHECK (KotStation IS NULL OR KotStation IN ('Kitchen', 'Bar')),
    KotStatus         NVARCHAR(20)     NOT NULL CONSTRAINT DF_OrderLines_KotStatus DEFAULT ('Pending')
                          CONSTRAINT CK_OrderLines_KotStatus CHECK (KotStatus IN ('Pending', 'Sent', 'Preparing', 'Ready', 'Served')),
    LineTotalAmount   DECIMAL(18,2)    NOT NULL,
    CreatedAtUtc      DATETIME2(3)     NOT NULL CONSTRAINT DF_OrderLines_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
    CreatedByUserId   UNIQUEIDENTIFIER NULL,
    ModifiedAtUtc     DATETIME2(3)     NULL,
    ModifiedByUserId  UNIQUEIDENTIFIER NULL,
    IsDeleted         BIT              NOT NULL CONSTRAINT DF_OrderLines_IsDeleted DEFAULT (0),
    CONSTRAINT PK_OrderLines PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_OrderLines_Order FOREIGN KEY (OrderId) REFERENCES Sales.Orders(Id),
    CONSTRAINT FK_OrderLines_Product FOREIGN KEY (ProductId) REFERENCES Masters.Products(Id)
);
GO
CREATE INDEX IX_OrderLines_OrderId ON Sales.OrderLines(OrderId) WHERE IsDeleted = 0;
GO

-- ---------------------------------------------------------------------------
-- Sales.OrderPayments
-- The Split Payment screen, one row per entry: any amount, any mode, an
-- optional label ("Guest 1"). SUM(Amount) WHERE OrderId = @x drives the
-- Paid/Remaining stats and whether the order can close.
-- ---------------------------------------------------------------------------
CREATE TABLE Sales.OrderPayments
(
    Id                UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_OrderPayments_Id DEFAULT (NEWSEQUENTIALID()),
    OrderId           UNIQUEIDENTIFIER NOT NULL,
    Amount            DECIMAL(18,2)    NOT NULL CONSTRAINT CK_OrderPayments_Amount CHECK (Amount > 0),
    PaymentMode       NVARCHAR(20)     NOT NULL CONSTRAINT CK_OrderPayments_PaymentMode
                          CHECK (PaymentMode IN ('Cash', 'Card', 'eSewa', 'Khalti', 'BankTransfer')),
    PaidByLabel       NVARCHAR(50)     NULL,             -- "Guest 1", "Guest 2" — free text, not a real identity
    CashierUserId     UNIQUEIDENTIFIER NOT NULL,
    PaidAtUtc         DATETIME2(3)     NOT NULL CONSTRAINT DF_OrderPayments_PaidAtUtc DEFAULT (SYSUTCDATETIME()),
    CreatedAtUtc      DATETIME2(3)     NOT NULL CONSTRAINT DF_OrderPayments_CreatedAtUtc DEFAULT (SYSUTCDATETIME()),
    CreatedByUserId   UNIQUEIDENTIFIER NULL,
    ModifiedAtUtc     DATETIME2(3)     NULL,
    ModifiedByUserId  UNIQUEIDENTIFIER NULL,
    IsDeleted         BIT              NOT NULL CONSTRAINT DF_OrderPayments_IsDeleted DEFAULT (0),
    CONSTRAINT PK_OrderPayments PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_OrderPayments_Order FOREIGN KEY (OrderId) REFERENCES Sales.Orders(Id),
    CONSTRAINT FK_OrderPayments_Cashier FOREIGN KEY (CashierUserId) REFERENCES Auth.Users(Id)
);
GO
CREATE INDEX IX_OrderPayments_OrderId ON Sales.OrderPayments(OrderId) WHERE IsDeleted = 0;
GO

-- ---------------------------------------------------------------------------
-- Sales.KotPrintLog
-- Audit trail of KOT print/reprint events — one row per print, grouped by
-- station so the kitchen and bar each get only their own items.
-- ---------------------------------------------------------------------------
CREATE TABLE Sales.KotPrintLog
(
    Id                UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_KotPrintLog_Id DEFAULT (NEWSEQUENTIALID()),
    OrderId           UNIQUEIDENTIFIER NOT NULL,
    Station           NVARCHAR(20)     NOT NULL CONSTRAINT CK_KotPrintLog_Station CHECK (Station IN ('Kitchen', 'Bar')),
    PrintedByUserId   UNIQUEIDENTIFIER NOT NULL,
    PrintedAtUtc      DATETIME2(3)     NOT NULL CONSTRAINT DF_KotPrintLog_PrintedAtUtc DEFAULT (SYSUTCDATETIME()),
    IsReprint         BIT              NOT NULL CONSTRAINT DF_KotPrintLog_IsReprint DEFAULT (0),
    CONSTRAINT PK_KotPrintLog PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_KotPrintLog_Order FOREIGN KEY (OrderId) REFERENCES Sales.Orders(Id),
    CONSTRAINT FK_KotPrintLog_User FOREIGN KEY (PrintedByUserId) REFERENCES Auth.Users(Id)
);
GO
CREATE INDEX IX_KotPrintLog_OrderId ON Sales.KotPrintLog(OrderId);
GO
